services:
  - type: web
    name: biloa-nguema-alphonse-kharel-24f2549
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: RENDER_EXTERNAL_URL
        sync: false
